
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author abc
 */
public class StaffInfo extends javax.swing.JFrame {


    /**
     * Creates new form StaffInfo
     */
    public StaffInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bdateTF = new javax.swing.JTextField();
        NumberTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        desTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelExit1 = new javax.swing.JLabel();
        jLabelMin1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTA = new javax.swing.JTextArea();
        jPanel15 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        staffID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        djoinTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panTF = new javax.swing.JTextField();
        expTF = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        view = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        staffCB = new javax.swing.JComboBox<>();
        branchCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        adharTF = new javax.swing.JTextField();
        Home = new javax.swing.JButton();

        jPanel14.setBackground(new java.awt.Color(44, 62, 80));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(236, 240, 241))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(236, 240, 241));
        jLabel21.setText("Student ID:");

        ID.setBackground(new java.awt.Color(204, 204, 255));
        ID.setForeground(new java.awt.Color(204, 204, 255));
        ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 255))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        bdateTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bdateTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        bdateTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        bdateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdateTFActionPerformed(evt);
            }
        });

        NumberTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NumberTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NumberTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        NumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberTFActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Branch:");

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setText("Add");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DOB:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Designation :");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Name :");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Phone No.:");

        nameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Official Mail id:");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Address:");

        emailTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        desTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        desTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        desTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        desTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desTFActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(108, 122, 137));

        jLabelExit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelExit1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit1.setText(" x");
        jLabelExit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelExit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExit1MouseClicked(evt);
            }
        });

        jLabelMin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMin1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin1.setText(" -");
        jLabelMin1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelMin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMin1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Staff Information");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMin1)
                        .addComponent(jLabelExit1))
                    .addComponent(jLabel5))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        addressTA.setColumns(20);
        addressTA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressTA.setRows(5);
        addressTA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(addressTA);

        jPanel15.setBackground(new java.awt.Color(44, 62, 80));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(236, 240, 241))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(236, 240, 241));
        jLabel22.setText("Staff ID:");

        staffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(staffID, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(staffID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date of Joining:");

        djoinTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        djoinTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PAN Card:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Experience:");

        panTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        panTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panTFActionPerformed(evt);
            }
        });

        expTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        expTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        view.setBackground(new java.awt.Color(255, 255, 255));
        view.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view.setText("View");
        view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setText("Staff:");

        staffCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Staff", "Teaching", "Non-Teaching" }));
        staffCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        branchCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        branchCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Branch", "CE", "IT", "EXTC", "ETRX", " " }));
        branchCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Aadhar Number:");

        adharTF.setColumns(12);
        adharTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        adharTF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adharTF.setDragEnabled(true);
        adharTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adharTFActionPerformed(evt);
            }
        });

        Home.setBackground(new java.awt.Color(0, 204, 153));
        Home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(0, 204, 153));
        Home.setIcon(new javax.swing.ImageIcon("C:\\Users\\abc\\Desktop\\BEPjt\\home.PNG")); // NOI18N
        Home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Home))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(216, 216, 216)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(djoinTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(NumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(desTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(update)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(staffCB, 0, 165, Short.MAX_VALUE)
                                                .addComponent(bdateTF)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(branchCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(adharTF)
                                    .addComponent(panTF)
                                    .addComponent(expTF)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Home)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(desTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(emailTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(djoinTF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(NumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffCB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(branchCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adharTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(delete)
                    .addComponent(view)
                    .addComponent(update))
                .addGap(40, 40, 40))
        );

        adharTF.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMin1MouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMin1MouseClicked

    private void jLabelExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExit1MouseClicked

    private void desTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if(nameTF.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Details are Empty");
                    nameTF.requestFocus();
                    return;
                    }
        if(desTF.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Enter the Designation");
                    desTF.requestFocus();
                    return;
                    }
        if(emailTF.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Email is empty");
                    emailTF.requestFocus();
                    return;
                    }
        if(djoinTF.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Mention Date Of Joining ");
                    djoinTF.requestFocus();
                    return;
                    }

        if(NumberTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Contact Info is empty");
                NumberTF.requestFocus();
                return;
                } 
               
        if(bdateTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Birth date is empty");
                bdateTF.requestFocus();
                return;
                }
        if(addressTA.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Address is empty");
                addressTA.requestFocus();
                return;
                }
        if(expTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Experience feild is empty");
                expTF.requestFocus();
                return;
                }
        if(adharTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Adhar detail is empty");
                adharTF.requestFocus();
                return;
                }
        if(panTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"PAN Card detail is empty");
                panTF.requestFocus();
                return;
                }


        String row = null;
        System.out.println("Add Clicked");
        try {
            PreparedStatement stat = DbConnection.getConnection("SELECT * FROM collegeerp.staff");
            ResultSet rs = stat.executeQuery();
            int value1 = 0;
            while (rs.next()) {
                value1 = rs.getRow();
            }
            int value = value1 + 1;
            String pattern = "000";
            DecimalFormat myFormatter = new DecimalFormat(pattern);
            row = myFormatter.format(value);
        } catch (Exception e1) {
            System.out.println(e1.toString());
            DbConnection.closeConnection();
        }

        try {
          
            PreparedStatement stat = DbConnection.getConnection("INSERT INTO collegeerp.staff(staffId,Name,Email_Id,Dob,Doj,Address,PanCard,AdharNo,P_Number,Designation,Experience,staff,Branch) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)");

            stat.setString(1, "KC" + branchCB.getSelectedItem() + row);
            stat.setString(2, nameTF.getText());
            stat.setString(3, emailTF.getText());
            stat.setString(4, bdateTF.getText());
            stat.setString(5, djoinTF.getText());
            stat.setString(6, addressTA.getText());
            stat.setString(7, panTF.getText());
            stat.setString(8, adharTF.getText());
            stat.setString(9, NumberTF.getText());
            stat.setString(10, desTF.getText());
            stat.setString(11, expTF.getText());
            stat.setString(12, (String) staffCB.getSelectedItem());
            stat.setString(13, (String) branchCB.getSelectedItem());
            stat.executeUpdate();

        } catch (Exception e) {
            System.out.print(e.toString());
        } finally {
            try {

            } catch (Exception e1) {
                System.out.println(e1.toString());
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void NumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberTFActionPerformed

    private void bdateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdateTFActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
if(staffID.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Please Enter your ID");
                    staffID.requestFocus();
                    return;
                    } 
System.out.println("Delete Clicked");
        try {
            PreparedStatement stat = DbConnection.getConnection("DELETE from collegeerp.staff where staffId = '" + staffID.getText() + "'");
            int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure?");
            if (result == JOptionPane.YES_OPTION) {
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data is Delete");

            }
        } catch (Exception e) {
            System.out.println(e.toString());
        } finally {
            try {
                // DbConnection.closeConnection();
            } catch (Exception e1) {
                System.out.println(e1.toString());
            }
        }
        System.out.println("Delete Clicked");  // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(staffID.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Please Enter your ID");
                    staffID.requestFocus();
                    return;
                    }        // TODO add your handling code here:
        if (update.getText().equals("Update")) {
            try {
                Editable();
                PreparedStatement stat = DbConnection.getConnection("Select * from collegeerp.staff where staffId ='" + staffID.getText() + "'");
                ResultSet rs = stat.executeQuery();
                while (rs.next()) {
                    nameTF.setText(rs.getString("Name"));
                    emailTF.setText(rs.getString("Email_Id"));
                    bdateTF.setText(rs.getString("Dob"));
                    djoinTF.setText(rs.getString("Doj"));
                    addressTA.setText(rs.getString("Address"));
                    panTF.setText(rs.getString("PanCard"));
                    adharTF.setText(rs.getString("AdharNo"));
                    NumberTF.setText(rs.getString("P_Number"));
                    desTF.setText(rs.getString("Designation"));
                    expTF.setText(rs.getString("Experience"));
                    staffCB.setSelectedItem(rs.getString("staff"));
                    branchCB.setSelectedItem(rs.getString("Branch"));

                    JOptionPane.showMessageDialog(null, "Now U can Update data");
                }
            } catch (Exception e) {
                System.out.println(e.toString());
            }
            update.setText("Update Data");
        } else if (update.getText().equals("Update Data")) {
            int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure?");
            if (result == JOptionPane.YES_OPTION) {
                try {

                    PreparedStatement stat = DbConnection.getConnection("UPDATE collegeerp.staff SET Name=?,Email_Id=?,Dob=?,Doj=?,Address=?,PanCard=?,Adharno=?,P_Number=?,Designation=?,Experience=?,staff=?,Branch=? where staffId='" + staffID.getText() + "'");
                    stat.setString(1, nameTF.getText());
                    stat.setString(2, emailTF.getText());
                    stat.setString(3, bdateTF.getText());
                    stat.setString(4, djoinTF.getText());
                    stat.setString(5, addressTA.getText());
                    stat.setString(6, panTF.getText());
                    stat.setString(7, adharTF.getText());
                    stat.setString(8, NumberTF.getText());
                    stat.setString(9, desTF.getText());
                    stat.setString(10, expTF.getText());
                    stat.setString(11, (String) staffCB.getSelectedItem());
                    stat.setString(12, (String) branchCB.getSelectedItem());

                    stat.executeUpdate();
                    update.setText("Update");
                    JOptionPane.showMessageDialog(null, "Staff Data is Updated");
                    Clear();
                } catch (Exception e) {
                    System.out.print(e.toString());
                } finally {
                    try {
                        DbConnection.closeConnection();
                    } catch (Exception e1) {
                        System.out.println(e1.toString());
                    }
                }

            }
        }
        System.out.println("Update Clicked");
    }//GEN-LAST:event_updateActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
if(staffID.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Please Enter your ID");
                    staffID.requestFocus();
                    return;
                    } 
try {
            PreparedStatement stat = DbConnection.getConnection("Select * from collegeerp.staff where staffId ='" + staffID.getText() + "'");
            ResultSet rs = stat.executeQuery();
            while (rs.next()) {
                nonEditable();
                nameTF.setText(rs.getString("Name"));
                emailTF.setText(rs.getString("Email_Id"));
                bdateTF.setText(rs.getString("Dob"));
                djoinTF.setText(rs.getString("Doj"));
                addressTA.setText(rs.getString("Address"));
                panTF.setText(rs.getString("PanCard"));
                adharTF.setText(rs.getString("AdharNo"));
                NumberTF.setText(rs.getString("P_Number"));
                desTF.setText(rs.getString("Designation"));
                expTF.setText(rs.getString("Experience"));
                staffCB.setSelectedItem(rs.getString("staff"));
                branchCB.setSelectedItem(rs.getString("Branch"));
            }
            JOptionPane.showMessageDialog(new JDialog(),"Invalid StaffID");
        } catch (Exception e) {
            System.out.println(e.toString());
        } finally {
            try {
                DbConnection.closeConnection();
            } catch (Exception e1) {
                System.out.println(e1.toString());
            }
        }
        System.out.println("View Clicked"); 
    }
        
        private void nonEditable() {
        nameTF.setEditable(false);
        emailTF.setEditable(false);
        bdateTF.setEditable(false);
       djoinTF.setEditable(false);
        addressTA.setEditable(false);
        panTF.setEditable(false);
        adharTF.setEditable(false);
        NumberTF.setEditable(false);
        desTF.setEditable(false);
        expTF.setEditable(false);
        }

        private void Editable() {
        nameTF.setEditable(true);
        emailTF.setEditable(true);
        bdateTF.setEditable(true);
        djoinTF.setEditable(true);
        addressTA.setEditable(true);
        panTF.setEditable(true);
        adharTF.setEditable(true);
        NumberTF.setEditable(true);
        desTF.setEditable(true);
        expTF.setEditable(true);
        }

        private void Clear() {
        nameTF.setText("");
        emailTF.setText("");
        bdateTF.setText("");
        djoinTF.setText("");
        addressTA.setText("");
        panTF.setText("");
        adharTF.setText("");
        NumberTF.setText("");
        desTF.setText("");
        expTF.setText("");
        staffCB.setSelectedItem("Select Staff");
        branchCB.setSelectedItem("Select Branch");

       
    // TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void staffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffIDActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Categories c;
        c = new Categories();
        c.setVisible(true);
        c.pack();
        c.setLocationRelativeTo(null);
        c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void adharTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adharTFActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_adharTFActionPerformed

    private void panTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panTFActionPerformed

      // TODO add your handling code here:
    }//GEN-LAST:event_panTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StaffInfo().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField NumberTF;
    private javax.swing.JButton add;
    private javax.swing.JTextArea addressTA;
    private javax.swing.JTextField adharTF;
    private javax.swing.JTextField bdateTF;
    private javax.swing.JComboBox<String> branchCB;
    private javax.swing.JButton delete;
    private javax.swing.JTextField desTF;
    private javax.swing.JTextField djoinTF;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField expTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelExit1;
    private javax.swing.JLabel jLabelMin1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField panTF;
    private javax.swing.JComboBox<String> staffCB;
    private javax.swing.JTextField staffID;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

}
