
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saurabh
 */
public class StudentInfo extends javax.swing.JFrame {
    String Bal="145000";
    String Paid="";
    public int remain;

    /**
     * Creates new form StudentInfo
     */
    public StudentInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameTF = new javax.swing.JTextField();
        branchCB = new javax.swing.JComboBox<>();
        emailTF = new javax.swing.JTextField();
        bdateTF = new javax.swing.JTextField();
        adminYearTF = new javax.swing.JTextField();
        NumberTF = new javax.swing.JTextField();
        pnoTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextArea();
        bgTF = new javax.swing.JTextField();
        aadharTF = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        view1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        receiptTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        amtTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ddTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        balanceL = new javax.swing.JLabel();
        Home = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        nameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        nameTF.setPreferredSize(new java.awt.Dimension(8, 25));
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        branchCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        branchCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Branch", "CE", "IT", "ETRX", "EXTC" }));
        branchCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchCBActionPerformed(evt);
            }
        });

        emailTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTF.setPreferredSize(new java.awt.Dimension(8, 25));
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        bdateTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bdateTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        bdateTF.setPreferredSize(new java.awt.Dimension(8, 25));
        bdateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdateTFActionPerformed(evt);
            }
        });

        adminYearTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminYearTF.setToolTipText(" ");
        adminYearTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        adminYearTF.setHighlighter(null);
        adminYearTF.setMaximumSize(new java.awt.Dimension(4, 4));
        adminYearTF.setMinimumSize(new java.awt.Dimension(4, 4));
        adminYearTF.setName(""); // NOI18N
        adminYearTF.setPreferredSize(new java.awt.Dimension(8, 25));
        adminYearTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminYearTFActionPerformed(evt);
            }
        });

        NumberTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NumberTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        NumberTF.setPreferredSize(new java.awt.Dimension(8, 25));
        NumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberTFActionPerformed(evt);
            }
        });

        pnoTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnoTF.setPreferredSize(new java.awt.Dimension(8, 25));

        addressTF.setColumns(20);
        addressTF.setRows(5);

        bgTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bgTF.setPreferredSize(new java.awt.Dimension(8, 25));

        aadharTF.setColumns(12);

        Add.setBackground(new java.awt.Color(204, 204, 204));
        Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add.setText("Add");
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        delete1.setBackground(new java.awt.Color(204, 204, 204));
        delete1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete1.setText("Delete");
        delete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });

        view1.setBackground(new java.awt.Color(204, 204, 204));
        view1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view1.setText("View");
        view1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Branch :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DOB :");

        jPanel14.setBackground(new java.awt.Color(0, 102, 102));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(236, 240, 241))); // NOI18N
        jPanel14.setForeground(new java.awt.Color(0, 102, 102));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Student ID:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel21)
                .addGap(37, 37, 37)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Admission Year :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Name :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Student Number :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email id :");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Address:");

        jPanel3.setBackground(new java.awt.Color(108, 122, 137));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Information");

        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setText(" x");
        jLabelExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText(" -");
        jLabelMin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMin)
                    .addComponent(jLabelExit))
                .addGap(23, 23, 23))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Parent Number :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Blood Group :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Aadhar Card:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fee Details :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reciept No. :");

        receiptTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        receiptTF.setToolTipText("");
        receiptTF.setPreferredSize(new java.awt.Dimension(8, 25));
        receiptTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptTFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Amount Paid:");

        amtTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amtTF.setPreferredSize(new java.awt.Dimension(8, 25));
        amtTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtTFActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel11.setText("eg. reciept no.1,reciept no.2.....");

        jLabel15.setText("eg. amt1,amt2.....");

        jLabel18.setText("eg. dd1,dd2.....");

        ddTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ddTF.setPreferredSize(new java.awt.Dimension(8, 25));
        ddTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddTFActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DD No.:");

        balanceL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        balanceL.setText("   ");

        Home.setBackground(new java.awt.Color(0, 204, 153));
        Home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(0, 204, 153));
        Home.setIcon(new javax.swing.ImageIcon("C:\\Users\\abc\\Desktop\\BEPjt\\home.PNG")); // NOI18N
        Home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnoTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(branchCB, javax.swing.GroupLayout.Alignment.LEADING, 0, 175, Short.MAX_VALUE)
                            .addComponent(nameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminYearTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bdateTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bgTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumberTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 36, Short.MAX_VALUE)
                        .addComponent(view1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(balanceL, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addressTF, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                            .addComponent(aadharTF)
                                            .addComponent(receiptTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(amtTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ddTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)))
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Home)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Home)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(branchCB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(adminYearTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aadharTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(balanceL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(receiptTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(amtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(jLabel18)))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receiptTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptTFActionPerformed

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
                if(ID.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Please Enter your ID");
                    ID.requestFocus();
                    return;
                    }
                
        try{
            PreparedStatement stat=DbConnection.getConnection("Select * from collegeerp.student where student_Id ='"+ID.getText()+"'");
            ResultSet rs = stat.executeQuery();
            while(rs.next()){
                nonEditable();
                nameTF.setText(rs.getString("Name"));
                branchCB.setSelectedItem(rs.getString("Branch"));
                emailTF.setText(rs.getString("Email_Id"));
                bdateTF.setText(rs.getString("Dob"));
                adminYearTF.setText(rs.getString("Year"));
                NumberTF.setText(rs.getString("S_Number"));
                pnoTF.setText(rs.getString("P_Number"));
                addressTF.setText(rs.getString("Address"));
                bgTF.setText(rs.getString("BgGroup"));
                aadharTF.setText(rs.getString("AdharNo"));
                
                Paid=rs.getString("AmountPaid");
                remain=Integer.parseInt(Bal)-Integer.parseInt(Paid);
                balanceL.setText("Balance = "+String.valueOf(remain));
                receiptTF.setText(rs.getString("RecieptNos"));
                amtTF.setText(rs.getString("AmountPaid"));
                ddTF.setText(rs.getString("DdNo"));
            }
            
        }
        catch(Exception e){
            System.out.println(e.toString());
        }finally{
            try{
                DbConnection.closeConnection();
            }catch(Exception e1){
                System.out.println(e1.toString());
            }
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_view1ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        if(ID.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Please Enter your ID");
                    ID.requestFocus();
                    return;
                    }
        try{
            PreparedStatement stat = DbConnection.getConnection("DELETE from collegeerp.student where student_Id = '"+ID.getText()+"'");
            int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure?");
            if (result == JOptionPane.YES_OPTION) {
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data is Delete");
                Clear();
            }
            
        }
        catch(Exception e){
            System.out.println(e.toString());
        }
        finally{
            try{
                DbConnection.closeConnection();
            }catch(Exception e1){
                System.out.println(e1.toString());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_delete1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(ID.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Please Enter your ID");
                    ID.requestFocus();
                    return;
                    }
        
        if(jButton1.getText().equals("Update")){
            try{
                Editable();
                PreparedStatement stat=DbConnection.getConnection("Select * from collegeerp.student where student_Id ='"+ID.getText()+"'");
                ResultSet rs = stat.executeQuery();
                while(rs.next()){
                    nameTF.setText(rs.getString("Name"));
                    branchCB.setSelectedItem(rs.getString("Branch"));
                    bdateTF.setText(rs.getString("Dob"));
                    addressTF.setText(rs.getString("Address"));
                    emailTF.setText(rs.getString("Email_Id"));
                    NumberTF.setText(rs.getString("S_Number"));
                    adminYearTF.setText(rs.getString("Year"));
                    pnoTF.setText(rs.getString("P_Number"));
                    bgTF.setText(rs.getString("BgGroup"));
                    aadharTF.setText(rs.getString("AdharNo"));
                    receiptTF.setText(rs.getString("RecieptNos"));
                    amtTF.setText(rs.getString("AmountPaid"));
                    Paid= rs.getString("AmountPaid");
                    ddTF.setText(rs.getString("DdNo"));
                    Bal=rs.getString("BalanceAmount");
                    balanceL.setText("Balance = "+rs.getString("BalanceAmount"));
                    JOptionPane.showMessageDialog(null, "Now U can Update data");
                }
            }
            catch(Exception e){
                System.out.println(e.toString());
            }
            jButton1.setText("Update Data");
        }else if(jButton1.getText().equals("Update Data")){
            int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure?");
            if (result == JOptionPane.YES_OPTION) {
                try{

                    PreparedStatement stat = DbConnection.getConnection("UPDATE collegeerp.student SET Name=?,Branch=?,Email_Id=?,Year=?,Dob=?,Address=?,S_Number=?,P_Number=?,BgGroup=?,AdharNo=?,RecieptNos=?,AmountPaid=?,DdNo=?,BalanceAmount=? where student_Id='"+ID.getText()+"'");

                    stat.setString(1,nameTF.getText());
                    stat.setString(2, (String) branchCB.getSelectedItem());
                    stat.setString(3,emailTF.getText());
                    stat.setString(4,adminYearTF.getText());
                    stat.setString(5,bdateTF.getText());
                    stat.setString(6,addressTF.getText());
                    stat.setString(7,NumberTF.getText());
                    stat.setString(8,pnoTF.getText());
                    stat.setString(9,bgTF.getText());
                    stat.setString(10,aadharTF.getText());
                    stat.setString(11,receiptTF.getText());
                    Paid=String.valueOf(Integer.parseInt(Paid)+Integer.parseInt(amtTF.getText()));
                    stat.setString(12,Paid);
                    stat.setString(13,ddTF.getText());
                    Bal=String.valueOf(Integer.parseInt(Bal)-Integer.parseInt(amtTF.getText()));
                    stat.setString(14,Bal);
                                        
                    

                    stat.executeUpdate();
                    jButton1.setText("Update");
                    JOptionPane.showMessageDialog(null, "Student Data is Updated");
                    Clear();
                }catch(Exception e){
                    System.out.print(e.toString());
                }finally{
                    try{
                        DbConnection.closeConnection();
                    }catch(Exception e1){
                        System.out.println(e1.toString());
                    }
                }

            }
        }

        System.out.println("Update Clicked");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if(nameTF.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"First Enter Your Details");
                    nameTF.requestFocus();
                    return;
                    }
        
        if(branchCB.getSelectedItem().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Select Your Branch");
                    branchCB.requestFocus();
                    return;
                    }
        if(emailTF.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Email is empty");
                    emailTF.requestFocus();
                    return;
                    }
        if(bdateTF.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(new JDialog(),"Birth-Date is empty");
                    bdateTF.requestFocus();
                    return;
                    }

        if(adminYearTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Enter Your Admission year");
                adminYearTF.requestFocus();
                return;
                }  
        
        if(NumberTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Contact Info is empty");
                NumberTF.requestFocus();
                return;
                }
        if(pnoTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Parent's Contact Info is empty");
                pnoTF.requestFocus();
                return;
                }
        if(addressTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Address is empty");
                addressTF.requestFocus();
                return;
                }
        if(aadharTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Parent's Contact Info is empty");
                aadharTF.requestFocus();
                return;
                }
        if(bgTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Blood Group is empty");
                bgTF.requestFocus();
                return;
                }
        if(receiptTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Enter your Receipt No.");
                receiptTF.requestFocus();
                return;
                }
        if(amtTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"Enter Total amount Paid");
                amtTF.requestFocus();
                return;
                }
        if(ddTF.getText().equals(""))
                {
                JOptionPane.showMessageDialog(new JDialog(),"DD No. is Empty");
                ddTF.requestFocus();
                return;
                }
        String row = null;
        try{
            PreparedStatement stat = DbConnection.getConnection("SELECT * FROM collegeerp.student");
            ResultSet rs = stat.executeQuery();
            int value1 = 0;
            while(rs.next()){
                value1 = rs.getRow();
            }
            int value = value1+1;
            String pattern="000";
            DecimalFormat myFormatter = new DecimalFormat(pattern);
            row = myFormatter.format(value);
        }catch(Exception e1){
            System.out.println(e1.toString());
            DbConnection.closeConnection();
        }
        try{
            PreparedStatement stat = DbConnection.getConnection("INSERT INTO collegeerp.student(student_Id,Name,Branch,Email_Id,Year,Dob,Address,S_Number,P_Number,BgGroup,AdharNo,RecieptNos,AmountPaid,DdNo,BalanceAmount) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            stat.setString(1,"E"+branchCB.getSelectedItem()+adminYearTF.getText()+row);
            stat.setString(2,nameTF.getText());
            stat.setString(3, (String) branchCB.getSelectedItem());
            stat.setString(4,emailTF.getText());
            stat.setString(5,adminYearTF.getText());
            stat.setString(6,bdateTF.getText());
            stat.setString(7,addressTF.getText());
            stat.setString(8,NumberTF.getText());
            stat.setString(9,pnoTF.getText());
            stat.setString(10,bgTF.getText());
            stat.setString(11,aadharTF.getText());
            stat.setString(12,receiptTF.getText());
            stat.setString(13,amtTF.getText());
            stat.setString(14,ddTF.getText());
            stat.setString(15,Bal);

            stat.executeUpdate();
            System.out.println("Student Is Added and id is "+"E"+branchCB.getSelectedItem()+adminYearTF.getText()+row);
            JOptionPane.showMessageDialog(null, "Student Added and id is "+"E"+branchCB.getSelectedItem()+adminYearTF.getText()+row);
            Clear();
        }catch(Exception e){
            System.out.print(e.toString());
        }finally{
            try{
                DbConnection.closeConnection();
            }catch(Exception e1){
                System.out.println(e1.toString());
            }
        }
    }//GEN-LAST:event_AddActionPerformed

    private void NumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberTFActionPerformed

    private void adminYearTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminYearTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminYearTFActionPerformed

    private void bdateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdateTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void amtTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amtTFActionPerformed

    private void ddTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddTFActionPerformed

    private void branchCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchCBActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Categories c;
        c = new Categories();
        c.setVisible(true);
        c.pack();
        c.setLocationRelativeTo(null);
        c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void nonEditable(){
        nameTF.setEditable(false);
        bdateTF.setEditable(false);
        addressTF.setEditable(false);
        emailTF.setEditable(false);
        NumberTF.setEditable(false);
        adminYearTF.setEditable(false);
        pnoTF.setEditable(false);
        bgTF.setEditable(false);
        aadharTF.setEditable(false);
        receiptTF.setEditable(false);
        amtTF.setEditable(false);
        ddTF.setEditable(false);
    }
    private void Editable(){
        nameTF.setEditable(true);
        bdateTF.setEditable(true);
        addressTF.setEditable(true);
        emailTF.setEditable(true);
        NumberTF.setEditable(true);
        adminYearTF.setEditable(true);
        pnoTF.setEditable(true);
        bgTF.setEditable(true);
        aadharTF.setEditable(true);
        receiptTF.setEditable(true);
        amtTF.setEditable(true);
        ddTF.setEditable(true);
    }
    private void Clear(){
        ID.setText("");
        nameTF.setText("");
        branchCB.setSelectedItem("Select Branch");
        bdateTF.setText("");
        addressTF.setText("");
        emailTF.setText("");
        NumberTF.setText("");
        adminYearTF.setText("");
        pnoTF.setText("");
        bgTF.setText("");
        aadharTF.setText("");
        receiptTF.setText("");
        amtTF.setText("");
        ddTF.setText("");
        balanceL.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Home;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField NumberTF;
    private javax.swing.JTextField aadharTF;
    private javax.swing.JTextArea addressTF;
    private javax.swing.JTextField adminYearTF;
    private javax.swing.JTextField amtTF;
    private javax.swing.JLabel balanceL;
    private javax.swing.JTextField bdateTF;
    private javax.swing.JTextField bgTF;
    private javax.swing.JComboBox<String> branchCB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField ddTF;
    private javax.swing.JButton delete1;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField pnoTF;
    private javax.swing.JTextField receiptTF;
    private javax.swing.JButton view1;
    // End of variables declaration//GEN-END:variables

}
